import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
//import './grafico/index'


export default function Home() {
  return (    
		  <div className="container-scroller">
        <Head>        
          <title>Sistema Auditoria</title>
          <meta name="description" content="Generated by create next app" />
          <meta charset="utf-8"/>
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
          <link rel="icon" href="/favicon.ico" />

           <Script src="../styles/vendors/js/vendor.bundle.base.js"/>
            <Script src="../styles/vendors/raphael/raphael.min.js"/>
            <Script src="../styles/vendors/morris.js/morris.min.js"/>
            <Script src="../styles/js/off-canvas.js"/>
            <Script src="../styles/js/hoverable-collapse.js"/>
            <Script src="../styles/js/misc.js"/>
            <Script src="../styles/js/settings.js"/>
            <Script src="../styles/js/todolist.js"/>
            <Script src="../styles/js/dashboard.js"/>
        </Head>
     <nav className="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div className="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a className="navbar-brand brand-logo" href="index.html"></a>
        <a className="navbar-brand brand-logo-mini" href="index.html"></a>
      </div>
      <div className="navbar-menu-wrapper d-flex align-items-center">
        <button className="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span className="mdi mdi-menu"></span>
        </button>
        <ul className="navbar-nav navbar-nav-left header-links d-none d-md-flex">
          <li className="nav-item">
            <a href="#" className="nav-link">Schedule <span className="badge badge-primary ml-1">New</span></a>
          </li>
          <li className="nav-item active">
            <a href="#" className="nav-link"><i className="mdi mdi-elevation-rise"></i>Reports</a>
          </li>
          <li className="nav-item">
            <a href="#" className="nav-link"><i className="mdi mdi-bookmark-plus-outline"></i>Score</a>
          </li>
        </ul>
        <ul className="navbar-nav navbar-nav-right">
          <li className="nav-item dropdown">
            <a className="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <i className="mdi mdi-message-text-outline"></i>
              <span className="count bg-warning">2</span>
            </a>
            <div className="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
              <div className="dropdown-item py-3">
                <p className="mb-0 font-weight-medium float-left">You have 7 unread mails
                </p>
                <span className="badge badge-inverse-info badge-pill float-right">View all</span>
              </div>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
				  
                </div>
                <div className="preview-item-content flex-grow">
                  <h6 className="preview-subject ellipsis font-weight-normal text-dark mb-1">David Grey
                    <span className="float-right font-weight-light small-text text-gray">1 Minutes ago</span>
                  </h6>
                  <p className="font-weight-light small-text mb-0">
                    The meeting is cancelled
                  </p>
                </div>
              </a>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
				  
                </div>
                <div className="preview-item-content flex-grow">
                  <h6 className="preview-subject ellipsis font-weight-normal text-dark mb-1">Tim Cook
                    <span className="float-right font-weight-light small-text text-gray">15 Minutes ago</span>
                  </h6>
                  <p className="font-weight-light small-text mb-0">
                    New product launch
                  </p>
                </div>
              </a>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
				  
                </div>
                <div className="preview-item-content flex-grow">
                  <h6 className="preview-subject ellipsis font-weight-normal text-dark mb-1"> Johnson
                    <span className="float-right font-weight-light small-text text-gray">18 Minutes ago</span>
                  </h6>
                  <p className="font-weight-light small-text mb-0">
                    Upcoming board meeting
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li className="nav-item dropdown">
            <a className="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i className="mdi mdi-bell-outline"></i>
              <span className="count bg-success">4</span>
            </a>
            <div className="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
              <a className="dropdown-item py-3">
                <p className="mb-0 font-weight-medium float-left">You have 4 new notifications
                </p>
                <span className="badge badge-pill badge-inverse-info float-right">View all</span>
              </a>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
                  <div className="preview-icon bg-inverse-success">
                    <i className="mdi mdi-alert-circle-outline mx-0"></i>
                  </div>
                </div>
                <div className="preview-item-content">
                  <h6 className="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
                  <p className="font-weight-light small-text mb-0">
                    Just now
                  </p>
                </div>
              </a>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
                  <div className="preview-icon bg-inverse-warning">
                    <i className="mdi mdi-comment-text-outline mx-0"></i>
                  </div>
                </div>
                <div className="preview-item-content">
                  <h6 className="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
                  <p className="font-weight-light small-text mb-0">
                    Private message
                  </p>
                </div>
              </a>
              <div className="dropdown-divider"></div>
              <a className="dropdown-item preview-item">
                <div className="preview-thumbnail">
                  <div className="preview-icon bg-inverse-info">
                    <i className="mdi mdi-email-outline mx-0"></i>
                  </div>
                </div>
                <div className="preview-item-content">
                  <h6 className="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
                  <p className="font-weight-light small-text mb-0">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li className="nav-item d-none d-lg-block color-setting">
            <a className="nav-link" href="#">
              <i className="mdi mdi-tune"></i>
            </a>
          </li>
          <li className="nav-item dropdown d-none d-xl-inline-block">
            <a className="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span className="mr-3">Hello, Sebastian !</span>
            </a>
            <div className="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a className="dropdown-item p-0">
                <div className="d-flex border-bottom">
                  <div className="py-3 px-4 d-flex align-items-center justify-content-center"><i className="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i></div>
                  <div className="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right"><i className="mdi mdi-account-outline mr-0 text-gray"></i></div>
                  <div className="py-3 px-4 d-flex align-items-center justify-content-center"><i className="mdi mdi-alarm-check mr-0 text-gray"></i></div>
                </div>
              </a>
              <a className="dropdown-item mt-2">
                Manage Accounts
              </a>
              <a className="dropdown-item">
                Change Password
              </a>
              <a className="dropdown-item">
                Check Inbox
              </a>
              <a className="dropdown-item">
                Sign Out
              </a>
            </div>
          </li>
        </ul>
        <button className="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span className="icon-menu"></span>
        </button>
      </div>
    </nav>
    <div className="container-fluid page-body-wrapper">
      <div className="theme-setting-wrapper">
        <div id="theme-settings" className="settings-panel">
          <i className="settings-close mdi mdi-close"></i>
          <div className="d-flex align-items-center justify-content-between border-bottom">
            <p className="settings-heading font-weight-bold border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0">Template Skins</p>
          </div>
          <div className="sidebar-bg-options selected" id="sidebar-dark-theme"><div className="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
          <div className="sidebar-bg-options" id="sidebar-light-theme"><div className="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
          <p className="settings-heading font-weight-bold mt-2">Header Skins</p>
          <div className="color-tiles mx-0 px-4">
            <div className="tiles primary"></div>
            <div className="tiles success"></div>
            <div className="tiles warning"></div>
            <div className="tiles danger"></div>
            <div className="tiles pink"></div>
            <div className="tiles info"></div>
            <div className="tiles dark"></div>
            <div className="tiles default"></div>
          </div>
        </div>
      </div>
      <div id="right-sidebar" className="settings-panel">
        <i className="settings-close mdi mdi-close"></i>
        <div className="d-flex align-items-center justify-content-between border-bottom">
          <p className="settings-heading font-weight-bold border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0">Friends</p>
        </div>
        <ul className="chat-list">
          <li className="list active">
            <div className="profile"><span className="online"></span></div>
            <div className="info">
              <p>Thomas Douglas</p>
              <p>Available</p>
            </div>
            <small className="text-muted my-auto">19 min</small>
          </li>
          <li className="list">
            <div className="profile"><span className="offline"></span></div>
            <div className="info">
              <div className="wrapper d-flex">
                <p>Catherine</p>
              </div>
              <p>Away</p>
            </div>
            <div className="badge badge-success badge-pill my-auto mx-2">4</div>
            <small className="text-muted my-auto">23 min</small>
          </li>
          <li className="list">
            <div className="profile"><span className="online"></span></div>
            <div className="info">
              <p>Daniel Russell</p>
              <p>Available</p>
            </div>
            <small className="text-muted my-auto">14 min</small>
          </li>
          <li className="list">
            <div className="profile"><span className="offline"></span></div>
            <div className="info">
              <p>James Richardson</p>
              <p>Away</p>
            </div>
            <small className="text-muted my-auto">2 min</small>
          </li>
          <li className="list">
            <div className="profile"><span className="online"></span></div>
            <div className="info">
              <p>Madeline Kennedy</p>
              <p>Available</p>
            </div>
            <small className="text-muted my-auto">5 min</small>
          </li>
          <li className="list">
            <div className="profile"><span className="online"></span></div>
            <div className="info">
              <p>Sarah Graves</p>
              <p>Available</p>
            </div>
            <small className="text-muted my-auto">47 min</small>
          </li>
        </ul>
      </div>
      <nav className="sidebar sidebar-offcanvas" id="sidebar">
        <ul className="nav">
          <li className="nav-item nav-profile">
            <div className="nav-link">
              <div className="profile-image">  <span className="online-status online"></span> </div>
              <div className="profile-name">
                <p className="name">Sebastian Brayden</p>
                <p className="designation">UI/UX Designer</p>
              </div>
              <div className="notification-panel mt-4">
                <span><i className="mdi mdi-settings"></i></span>
                <span className="count-wrapper"><i className="mdi mdi-bell"></i><span className="count top-right bg-warning">4</span></span>
                <span><i className="mdi mdi-email"></i></span>
              </div>
            </div>
          </li>
          <li className="nav-item"> <a className="nav-link" href="index.html">  <span className="menu-title">Dashboard</span></a> </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#page-layouts" aria-expanded="false" aria-controls="page-layouts">  <span className="menu-title">Page Layouts</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="page-layouts">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/layout/boxed-layout.html">Boxed</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/rtl-layout.html">RTL</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/horizontal-menu.html">Horizontal Menu</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/horizontal-menu-2.html">Horizontal Menu 2</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#apps-dropdown" aria-expanded="false" aria-controls="apps-dropdown"> <span className="menu-title">Apps</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="apps-dropdown">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/apps/email.html">E-mail</a> </li>
                <li className="nav-item"> <a className="nav-link" href="pages/apps/calendar.html">Calendar</a> </li>
                <li className="nav-item"> <a className="nav-link" href="pages/apps/todo.html">Todo List</a> </li>
                <li className="nav-item"> <a className="nav-link" href="pages/apps/gallery.html">Gallery</a> </li>
              </ul>
            </div>
          </li>
          <li className="nav-item"> <a className="nav-link" href="pages/widgets.html">  <span className="menu-title">Widgets</span> </a> </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#sidebar-layouts" aria-expanded="false" aria-controls="sidebar-layouts"> <span className="menu-title">Sidebar Layouts</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="sidebar-layouts">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/layout/compact-menu.html">Compact menu</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/sidebar-collapsed.html">Icon menu</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/sidebar-hidden.html">Sidebar Hidden</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/sidebar-hidden-overlay.html">Sidebar Overlay</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/layout/sidebar-fixed.html">Sidebar Fixed</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic"> <span className="menu-title">Basic UI Elements</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="ui-basic">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/accordions.html">Accordions</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/badges.html">Badges</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/breadcrumbs.html">Breadcrumbs</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/modals.html">Modals</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/progress.html">Progress bar</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/pagination.html">Pagination</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/tabs.html">Tabs</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/typography.html">Typography</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/tooltips.html">Tooltips</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#ui-advanced" aria-expanded="false" aria-controls="ui-advanced">  <span className="menu-title">Advanced Elements</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="ui-advanced">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/dragula.html">Dragula</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/clipboard.html">Clipboard</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/context-menu.html">Context menu</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/slider.html">Sliders</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/carousel.html">Carousel</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/colcade.html">Colcade</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/ui-features/loaders.html">Loaders</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">  <span className="menu-title">Form elements</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="form-elements">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"><a className="nav-link" href="pages/forms/basic_elements.html">Basic Elements</a></li>
                <li className="nav-item"><a className="nav-link" href="pages/forms/advanced_elements.html">Advanced Elements</a></li>
                <li className="nav-item"><a className="nav-link" href="pages/forms/validation.html">Validation</a></li>
                <li className="nav-item"><a className="nav-link" href="pages/forms/wizard.html">Wizard</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#editors" aria-expanded="false" aria-controls="editors">  <span className="menu-title">Editors</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="editors">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"><a className="nav-link" href="pages/forms/text_editor.html">Text editors</a></li>
                <li className="nav-item"><a className="nav-link" href="pages/forms/code_editor.html">Code editors</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#charts" aria-expanded="false" aria-controls="charts">  <span className="menu-title">Charts</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="charts">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/charts/chartjs.html">ChartJs</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/morris.html">Morris</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/flot-chart.html">Flot</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/google-charts.html">Google charts</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/sparkline.html">Sparkline js</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/c3.html">C3 charts</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/chartist.html">Chartists</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/charts/justGage.html">JustGage</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#tables" aria-expanded="false" aria-controls="tables"> <span className="menu-title">Tables</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="tables">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/tables/basic-table.html">Basic table</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/tables/data-table.html">Data table</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/tables/js-grid.html">Js-grid</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/tables/sortable-table.html">Sortable table</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item"> <a className="nav-link" href="pages/ui-features/popups.html">  <span className="menu-title">Popups</span> </a> </li>
          <li className="nav-item"> <a className="nav-link" href="pages/ui-features/notifications.html">  <span className="menu-title">Notifications</span> </a> </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#icons" aria-expanded="false" aria-controls="icons">  <span className="menu-title">Icons</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="icons">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/icons/flag-icons.html">Flag icons</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/icons/font-awesome.html">Font Awesome</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/icons/simple-line-icon.html">Simple line icons</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/icons/themify.html">Themify icons</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#maps" aria-expanded="false" aria-controls="maps">  <span className="menu-title">Maps</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="maps">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/maps/mapeal.html">Mapeal</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/maps/vector-map.html">Vector Map</a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/maps/google-maps.html">Google Map</a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth"> <span className="menu-title">User Pages</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="auth">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/samples/login.html"> Login </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/login-2.html"> Login 2 </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/register.html"> Register </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/register-2.html"> Register 2 </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/lock-screen.html"> Lockscreen </a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#error" aria-expanded="false" aria-controls="error">  <span className="menu-title">Error pages</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="error">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/samples/error-404.html"> 404 </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/error-500.html"> 500 </a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages"> <span className="menu-title">General Pages</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="general-pages">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/samples/blank-page.html"> Blank Page </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/landing-page.html"> Landing Page </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/profile.html"> Profile </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/faq.html"> FAQ </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/faq-2.html"> FAQ 2 </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/news-grid.html"> News grid </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/timeline.html"> Timeline </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/search-results.html"> Search Results </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/portfolio.html"> Portfolio </a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item">
            <a className="nav-link" data-toggle="collapse" href="#e-commerce" aria-expanded="false" aria-controls="e-commerce"> <span className="menu-title">E-commerce</span><i className="menu-arrow"></i></a>
            <div className="collapse" id="e-commerce">
              <ul className="nav flex-column sub-menu">
                <li className="nav-item"> <a className="nav-link" href="pages/samples/invoice.html"> Invoice </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/pricing-table.html"> Pricing Table </a></li>
                <li className="nav-item"> <a className="nav-link" href="pages/samples/orders.html"> Orders </a></li>
              </ul>
            </div>
          </li>
          <li className="nav-item"> <a className="nav-link" href="pages/documentation.html"> <span className="menu-title">Documentation</span> </a> </li>
          <li className="nav-item">
            <div className="sidebar-sticker">
              <div className="d-flex align-items-center text-primary">
                <h6 className="mb-1">Need Help</h6><i className="mdi ml-2 mdi-bell-ring-outline"></i>
              </div>
              <a className="d-block text-gray my-2" href="#">hello@website.com</a>
              <a className="d-block" href="#">Visit FAQ</a>
            </div>
          </li>
        </ul>
      </nav>
      <div className="main-panel">
        <div className="content-wrapper">
          <div className="row">
            <div className="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
              <div className="card card-statistics">
                <div className="card-body">
                  <div className="d-flex align-items-center justify-content-center">
                    <div className="highlight-icon bg-light mr-3">
                      <i className="mdi mdi-cube text-success icon-lg"></i>
                    </div>
                    <div className="wrapper">
                      <p className="card-text mb-0">Revenue</p>
                      <div className="fluid-container">
                        <h3 className="card-title mb-0">$65,650</h3>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
              <div className="card card-statistics">
                <div className="card-body">
                  <div className="d-flex align-items-center justify-content-center">
                    <div className="highlight-icon bg-light mr-3">
                      <i className="mdi mdi-briefcase-check text-primary icon-lg"></i>
                    </div>
                    <div className="wrapper">
                      <p className="card-text mb-0">Orders</p>
                      <div className="fluid-container">
                        <h3 className="card-title mb-0">$45,650</h3>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
              <div className="card card-statistics">
                <div className="card-body">
                  <div className="d-flex align-items-center justify-content-center">
                    <div className="highlight-icon bg-light mr-3">
                      <i className="mdi mdi-account-multiple text-danger icon-lg"></i>
                    </div>
                    <div className="wrapper">
                      <p className="card-text mb-0">Returns</p>
                      <div className="fluid-container">
                        <h3 className="card-title mb-0">$12,357</h3>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
              <div className="card card-statistics">
                <div className="card-body">
                  <div className="d-flex align-items-center justify-content-center">
                    <div className="highlight-icon bg-light mr-3">
                      <i className="mdi mdi-airballoon text-info icon-lg"></i>
                    </div>
                    <div className="wrapper">
                      <p className="card-text mb-0">Sales</p>
                      <div className="fluid-container">
                        <h3 className="card-title mb-0">$45,650</h3>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-4 col-sm-6 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title">Latest Comments</h5>
                  <div className="d-flex align-items-start pb-3 pt-1 mb-4 border-bottom">
                    
                    <div className="wrapper w-100 pl-3">
                      <div className="d-flex align-items-center justify-content-between">
                        <span className="badge badge-danger badge-lg mb-2">ADMIN-APPLE</span>
                        <span className="text-gray text-small">13:17 PM</span>
                      </div>
                      <p>A new rating has been received</p>
                    </div>
                  </div>
                  <div className="d-flex align-items-start pb-3 pt-1 mb-4 border-bottom">
                    
                    <div className="wrapper w-100 pl-3">
                      <div className="d-flex align-items-center justify-content-between">
                        <span className="badge badge-warning badge-lg mb-2">ADMIN-AIRBNB</span>
                        <span className="text-gray text-small">09:29 PM</span>
                      </div>
                      <p>Verify your email address !</p>
                    </div>
                  </div>
                  <div className="d-flex align-items-start pb-3 pt-1 mb-4 border-bottom">
                    
                    <div className="wrapper w-100 pl-3">
                      <div className="d-flex align-items-center justify-content-between">
                        <span className="badge badge-success badge-lg mb-2">ADMIN-AMAZON</span>
                        <span className="text-gray text-small">03:43 AM</span>
                      </div>
                      <p>Support of theme</p>
                    </div>
                  </div>
                  <div className="d-flex align-items-start pt-1">
                   
                    <div className="wrapper w-100 pl-3">
                      <div className="d-flex align-items-center justify-content-between">
                        <span className="badge badge-info badge-lg mb-2">ADMIN-FACEBOOK</span>
                        <span className="text-gray text-small">10:14 AM</span>
                      </div>
                      <p>New submission on website</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-4 col-sm-6 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title">Top Selling Products</h5>
                  <div className="row border-bottom pb-3 mb-3">
                    <div className="col-12 py-4 my-3">
                    <div id="DashboardBarChart1" Style={{height:"100px"}} ></div>
                    </div>
                    <div className="col-12 mt-3">
                      <div className="d-flex align-items-end">
                        <h1 className="display-4 font-weight-semibold mb-0">8935</h1>
                        <h5 className="ml-3 mb-2">Sales Per Day</h5>
                      </div>
                      <p className="mt-0 mb-2">Some quick example text to build</p>
                      <div className="d-flex align-items-center">
                        <div className="progress progress-md w-100 mr-3">
                          <div className="progress-bar bg-success" role="progressbar" ></div>
                        </div>
                        <p className="mb-0">38%</p>
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-md-12">
                      <div className="d-flex align-items-end">
                        <h1 className="display-4 font-weight-semibold mb-0">6843</h1>
                        <h5 className="ml-3 mb-2">Orders Per Day</h5>
                      </div>
                      <p className="mt-0 mb-2">Proin eget tortor risus.</p>
                      <div className="d-flex align-items-center">
                        <div className="progress progress-md w-100 mr-3">
                          <div className="progress-bar bg-primary" role="progressbar" ></div>
                        </div>
                        <p className="mb-0">64%</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-4 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title">Total Revenue</h5>
                  <div className="w-75 mx-auto">
                    <div className="d-flex justify-content-between text-center mb-2">
                      <div className="wrapper">
                        <h4>6,256</h4>
                        <small className="text-muted">Totel sales</small>
                      </div>
                      <div className="wrapper">
                        <h4>8569</h4>
                        <small className="text-muted">Open Compaign</small>
                      </div>
                    </div>
                  </div>
                  <div id="morris-line-example"></div>
                  <div className="w-75 mx-auto">
                    <div className="d-flex justify-content-between text-center mt-5">
                      <div className="wrapper">
                        <h4>5136</h4>
                        <small className="text-muted">Online Sales</small>
                      </div>
                      <div className="wrapper">
                        <h4>4596</h4>
                        <small className="text-muted">Store Sales</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-12 grid-margin">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title mb-4">Order Status</h5>
                  <div className="row mb-5">
                    <div className="col-md-3 col-sm-6 col-6">
                      <div className="d-flex">
                        <h2 className="mb-0">5675</h2>
                        <i className="mdi mdi-arrow-up h2 mb-0 text-success"></i>
                      </div>
                      <p>Daily Order</p>
                    </div>
                    <div className="col-md-3 col-sm-6 col-6">
                      <div className="d-flex">
                        <h2 className="mb-0">7841</h2>
                        <i className="mdi mdi-arrow-up h2 mb-0 text-success"></i>
                      </div>
                      <p>Tasks Completed</p>
                    </div>
                    <div className="col-md-3 col-sm-6 col-6">
                      <div className="d-flex">
                        <h2 className="mb-0">6521</h2>
                        <i className="mdi mdi-arrow-down h2 mb-0 text-danger"></i>
                      </div>
                      <p>Monthly Sales</p>
                    </div>
                    <div className="col-md-3 col-sm-6 col-6">
                      <div className="d-flex">
                        <h2 className="mb-0">8954</h2>
                        <i className="mdi mdi-arrow-up h2 mb-0 text-success"></i>
                      </div>
                      <p>Total Revenue</p>
                    </div>
                  </div>
                  <canvas id="dashoard-area-chart" height="70"></canvas>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-5 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <div className="d-flex align-items-center justify-content-between mb-4">
                    <h5 className="card-title mb-0">New Accounts</h5>
                    <small className="text-gray d-none d-sm-block">Last activity was 2 days ago</small>
                  </div>
                  <div className="new-accounts">
                    <ul className="chats">
                      <li className="chat-persons">
                        <a href="#">
                          <span className="pro-pic"></span>
                          <div className="user">
                            <p className="u-name">David</p>
                            <p className="u-designation">Python Developer</p>
                          </div>
                          <p className="joined-date">30 Mins ago</p>
                        </a>
                      </li>
                      <li className="chat-persons">
                        <a href="#">
                          <span className="pro-pic"></span>
                          <div className="user">
                            <p className="u-name">Stella Johnson</p>
                            <p className="u-designation">SEO Expert</p>
                          </div>
                          <p className="joined-date">2 Days ago</p>
                        </a>
                      </li>
                      <li className="chat-persons">
                        <a href="#">
                          <span className="pro-pic"></span>
                          <div className="user">
                            <p className="u-name">Marina Michel</p>
                            <p className="u-designation">Business Development</p>
                          </div>
                          <p className="joined-date">4 Days ago</p>
                        </a>
                      </li>
                      <li className="chat-persons">
                        <a href="#">
                          <span className="pro-pic"></span>
                          <div className="user">
                            <p className="u-name">Edward Fletcher</p>
                            <p className="u-designation">UI/UX Designer</p>
                          </div>
                          <p className="joined-date">5 Days ago</p>
                        </a>
                      </li>
                      <li className="chat-persons">
                        <a href="#">
                          <span className="pro-pic"></span>
                          <div className="user">
                            <p className="u-name">Allen Donald</p>
                            <p className="u-designation">UI/UX Designer</p>
                          </div>
                          <p className="joined-date">5 Days ago</p>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-7 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <div className="d-flex justify-content-between align-items-center mb-4">
                    <h5 className="card-title mb-0">To-do list</h5>
                    <button type="button" className="btn btn-sm btn-success ml-auto"><i className="mdi mdi-plus"></i>Create New</button>
                  </div>
                  <div className="todo-list-container">
  									<div className="list-wrapper">
  										<ul className="todo-list">
                        <li className="list">
                          <div className="form-check form-check-flat todo-form-check w-100">
                            <div className="form-check-label">
                              <i className="input-helper"></i>
                              <div className="d-flex">
                                <div className="wrapper todo-content">
                                  <h6 className="mb-1 ellipsis">Anyways i would like just do it</h6>
                                  <p className="text-gray mb-0 ellipsor">15:00 PM Mon, 14 Jan 2018</p>
                                  <span className="text-success ellipsor">#Photoshop</span>
                                </div>
                                <div className="action-wrapper wrapper ml-auto d-flex align-items-center">
                                  <i className="btn-close mdi mdi-close-circle-outline text-danger icon-md"></i>
                                  <i className="btn-action mdi mdi-dots-vertical text-muted icon-md"></i>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="list">
                          <div className="form-check form-check-flat todo-form-check w-100">
                            <div className="form-check-label">
                              <i className="input-helper"></i>
                              <div className="d-flex">
                                <div className="wrapper todo-content">
                                  <h6 className="mb-1 ellipsis">Make an appointment with Doctor</h6>
                                  <p className="text-gray mb-0 ellipsor">10:00 PM Sat, 10 Jan 2018</p>
                                  <span className="text-success ellipsor">#Bootstrap</span>
                                </div>
                                <div className="action-wrapper wrapper ml-auto d-flex align-items-center">
                                  <i className="btn-close mdi mdi-close-circle-outline text-danger icon-md"></i>
                                  <i className="btn-action mdi mdi-dots-vertical text-muted icon-md"></i>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="list">
                          <div className="form-check form-check-flat todo-form-check w-100">
                            <div className="form-check-label">
                              <i className="input-helper"></i>
                              <div className="d-flex">
                                <div className="wrapper todo-content">
                                  <h6 className="mb-1 ellipsis">Visit our boys in Battle Exhibition</h6>
                                  <p className="text-gray mb-0 ellipsor">06:46 PM Mon, 02 Jan 2018</p>
                                  <span className="text-success ellipsor">#Bootstrap&nbsp;&nbsp;#CSS</span>
                                </div>
                                <div className="action-wrapper wrapper ml-auto d-flex align-items-center">
                                  <i className="btn-close mdi mdi-close-circle-outline text-danger icon-md"></i>
                                  <i className="btn-action mdi mdi-dots-vertical text-muted icon-md"></i>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
                        <li className="list">
                          <div className="form-check form-check-flat todo-form-check w-100">
                            <div className="form-check-label">
                              <i className="input-helper"></i>
                              <div className="d-flex">
                                <div className="wrapper todo-content">
                                  <h6 className="mb-1 ellipsis">Please Checkout The Attachment</h6>
                                  <p className="text-gray mb-0 ellipsor">03:00 PM Sat, 13 Jan 2018</p>
                                  <span className="text-danger ellipsor">#HTML</span>
                                </div>
                                <div className="action-wrapper wrapper ml-auto d-flex align-items-center">
                                  <i className="btn-close mdi mdi-close-circle-outline text-danger icon-md"></i>
                                  <i className="btn-action mdi mdi-dots-vertical text-muted icon-md"></i>
                                </div>
                              </div>
                            </div>
                          </div>
                        </li>
  										</ul>
  									</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-12 grid-margin">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title">Payment Method</h5>
                  <div className="table-responsive">
                    <table className="table center-aligned-table">
                      <thead>
                        <tr>
                          <th className="border-bottom-0">ID</th>
                          <th className="border-bottom-0">Assignee</th>
                          <th className="border-bottom-0">Task Details</th>
                          <th className="border-bottom-0">Payment Method</th>
                          <th className="border-bottom-0">Payment Status</th>
                          <th className="border-bottom-0">Amount</th>
                          <th className="border-bottom-0">Tracking Number</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>#320</td>
                          <td>Mark C.Diaz</td>
                          <td>Support of thteme</td>
                          <td>Credit card</td>
                          <td><label className="badge badge-success">Approved</label></td>
                          <td>$12,245</td>
                          <td>JPBBN435893458</td>
                        </tr>
                        <tr>
                          <td>#321</td>
                          <td>Jose D</td>
                          <td>Verify your email address !</td>
                          <td>Internet banking</td>
                          <td><label className="badge badge-warning">Pending</label></td>
                          <td>$12,245</td>
                          <td>BDYBN435893325</td>
                        </tr>
                        <tr>
                          <td>#322</td>
                          <td>Philips T</td>
                          <td>Item support message send</td>
                          <td>Credit card</td>
                          <td><label className="badge badge-success">Approved</label></td>
                          <td>$12,245</td>
                          <td>JSNTN435884258</td>
                        </tr>
                        <tr>
                          <td>#323</td>
                          <td>Luke Pixel</td>
                          <td>New submission on website</td>
                          <td>Cash on delivery</td>
                          <td><label className="badge badge-danger">Rejected</label></td>
                          <td>$12,245</td>
                          <td>JPABT435893678</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div className="d-flex align-items-center mt-4">
                    <p className="mb-0 d-none d-md-block text-dark">Showing 1 to 20 of 20 entries</p>
                    <ul className="pagination mb-0 ml-auto">
                      <li className="page-item"><a className="page-link" href="#"><i className="mdi mdi-chevron-left"></i></a></li>
                      <li className="page-item active"><a className="page-link" href="#">1</a></li>
                      <li className="page-item"><a className="page-link" href="#">2</a></li>
                      <li className="page-item"><a className="page-link" href="#">3</a></li>
                      <li className="page-item"><a className="page-link" href="#">4</a></li>
                      <li className="page-item"><a className="page-link" href="#"><i className="mdi mdi-chevron-right"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6 grid-margin stretch-card">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title">The Current Chart</h5>
                  <canvas id="current-chart" height="100"></canvas>
                </div>
                <div className="border-top py-4 px-4">
                  <p className="mb-0 text-gray">Projects Status</p>
                  <div className="d-flex align-items-end">
                    <h2 className="mb-0 display-2 font-weight-semibold text-success">76,533</h2>
                    <p className="mb-2 ml-1 text-success">PCS</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-6 grid-margin stretch-card">
							<div className="card">
								<div className="card-body">
									<h5 className="card-title">Updates</h5>
									<ul className="bullet-line-list">
										<li>
											<h6>User confirmation</h6>
											<p className="mb-0">Donec rutrum congue leo eget malesuada.</p>
											<p className="text-muted">
												<i className="mdi mdi-clock"></i>
												7 months ago.
											</p>
										</li>
										<li>
											<h6>Continuous evaluation</h6>
											<p className="mb-0">Vivamus suscipit tortor eget felis porttitor volutpat.</p>
											<p className="text-muted">
												<i className="mdi mdi-clock"></i>
												7 months ago.
											</p>
										</li>
										<li>
											<h6>Promotion</h6>
											<p className="mb-0">Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.</p>
											<p className="text-muted">
												<i className="mdi mdi-clock"></i>
												7 months ago.
											</p>
										</li>
									</ul>
								</div>
							</div>
						</div>
          </div>
          <div className="row">
            <div className="col-12 grid-margin">
              <div className="card">
                <div className="card-body">
                  <h5 className="card-title mb-4">Manage Tickets</h5>
                  <div className="fluid-container">
                    <div className="row ticket-card mt-3 pb-2 border-bottom pb-3 mb-3">
                      <div className="col-md-1">
                        
                      </div>
                      <div className="ticket-details col-md-9">
                        <div className="d-flex">
                          <p className="text-dark font-weight-bold mr-2 mb-0 no-wrap">James :</p>
                          <p className="font-weight-medium mr-1 mb-0">[#23047]</p>
                          <p className="font-weight-semibold mb-0 ellipsis">Donec rutrum congue leo eget malesuada.</p>
                        </div>
                        <p className="text-small text-gray mb-2">Donec rutrum congue leo eget malesuada. Quisque velit nisi, pretium ut lacinia in, elementum id enim vivamus.</p>
                        <div className="row text-gray d-md-flex d-none">
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted text-muted">Last responded :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted text-muted">3 hours ago</p>
                          </div>
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted text-muted">Due in :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted text-muted">2 Days</p>
                          </div>
                        </div>
                      </div>
                      <div className="ticket-actions col-md-2">
                        <div className="btn-group dropdown">
                          <button type="button" className="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                          </button>
                          <div className="dropdown-menu">
                            <a className="dropdown-item" href="#"><i className="fa fa-reply fa-fw"></i>Quick reply</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-history fa-fw"></i>Another action</a>
                            <div className="dropdown-divider"></div>
                            <a className="dropdown-item" href="#"><i className="fa fa-check text-success fa-fw"></i>Resolve Issue</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-times text-danger fa-fw"></i>Close Issue</a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="row ticket-card mt-3 pb-2 border-bottom pb-3 mb-3">
                      <div className="col-md-1">
                        
                      </div>
                      <div className="ticket-details col-md-9">
                        <div className="d-flex">
                          <p className="text-dark font-weight-bold mr-2 mb-0 no-wrap">Stella :</p>
                          <p className="font-weight-medium mr-1 mb-0">[#23135]</p>
                          <p className="font-weight-semibold mb-0 ellipsis">Curabitur aliquet quam id dui posuere blandit.</p>
                        </div>
                        <p className="text-small text-gray mb-2">Pellentesque in ipsum id orci porta dapibus. Sed porttitor lectus nibh. Curabitur non nulla sit amet nisl.</p>
                        <div className="row text-gray d-md-flex d-none">
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted">Last responded :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted">3 hours ago</p>
                          </div>
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted">Due in :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted">2 Days</p>
                          </div>
                        </div>
                      </div>
                      <div className="ticket-actions col-md-2">
                        <div className="btn-group dropdown">
                          <button type="button" className="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                          </button>
                          <div className="dropdown-menu">
                            <a className="dropdown-item" href="#"><i className="fa fa-reply fa-fw"></i>Quick reply</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-history fa-fw"></i>Another action</a>
                            <div className="dropdown-divider"></div>
                            <a className="dropdown-item" href="#"><i className="fa fa-check text-success fa-fw"></i>Resolve Issue</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-times text-danger fa-fw"></i>Close Issue</a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="row ticket-card mt-3">
                      <div className="col-md-1">
                        
                      </div>
                      <div className="ticket-details col-md-9">
                        <div className="d-flex">
                          <p className="text-dark font-weight-bold mr-2 mb-0 no-wrap">John Doe :</p>
                          <p className="font-weight-medium mr-1 mb-0">[#23246]</p>
                          <p className="font-weight-semibold mb-0 ellipsis">Mauris blandit aliquet elit, eget tincidunt nibh pulvinar.</p>
                        </div>
                        <p className="text-small text-gray mb-2">Nulla quis lorem ut libero malesuada feugiat. Proin eget tortor risus. Lorem ipsum dolor sit amet.</p>
                        <div className="row text-gray d-md-flex d-none">
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted">Last responded :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted">3 hours ago</p>
                          </div>
                          <div className="col-4 d-flex">
                            <p className="mb-0 mr-2 text-muted">Due in :</p>
                            <p className="Last-responded mr-2 mb-0 text-muted">2 Days</p>
                          </div>
                        </div>
                      </div>
                      <div className="ticket-actions col-md-2">
                        <div className="btn-group dropdown">
                          <button type="button" className="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                          </button>
                          <div className="dropdown-menu">
                            <a className="dropdown-item" href="#"><i className="fa fa-reply fa-fw"></i>Quick reply</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-history fa-fw"></i>Another action</a>
                            <div className="dropdown-divider"></div>
                            <a className="dropdown-item" href="#"><i className="fa fa-check text-success fa-fw"></i>Resolve Issue</a>
                            <a className="dropdown-item" href="#"><i className="fa fa-times text-danger fa-fw"></i>Close Issue</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <footer className="footer">
          <div className="container-fluid clearfix">
            <span className="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018 <a href="http://www.urbanui.com/" target="_blank">Urbanui</a>. All rights reserved.</span>
            <span className="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i className="mdi mdi-heart text-danger"></i></span>
          </div>
        </footer>
      </div>
    </div>
  </div>
  )
}
